language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJTQHLCZHU6QOGSWA
  secret_access_key:
    secure: fjMr4DuL0/NETMSunb3nrN/Jmf3b/37od/eg/6MQY075vIhirdWBnTg6dhM0q4FiryNk9V56rGCdo7ovhMKTfgW3tTENTDgl943TV4iajoFKsAhdZDT/2Ok2C6w/EW4+a1vNYXKJM3wMMkaVNpsESzcSMj6ilI+epk9aKm+b/nbl+p4nKmUKgVyoA9zek5iKwWUoRBgqpFJ9Ki0MrBZAC442eKSLhIBkD9I8dvaZ0DjKxwc/D/SRcQbYFPdT4YjaglhmBtYJIixeY40JsBLW5vgqalZreKDQUiIX3bT7C7dvd06HvNBCL1JTz+iAtKuaABoWdiVE5el4vfg05IzW4bgJsQab938YNV94HudwiDbigud8HTqyQiw1MpAoyQTu+tkZz5+ZcsGL8BCMdenEoyKq7vmx+jX1Im/NMp4WVX7aaEMI8zWyF2CI3AWrMfQWqkuFgil4zM3kLwTbQS618AOiDZQAJA4nrn9Q/uP5k0ySC5w+lTiOAkW9JG2+5f8YDW3+BBddxtBsjBi7X15Axt3TuRzEkMTZ723jgLacNzTTwjdSU8GfB3lo6W93M5HkLkzirYa61YumsM5YVcwHGpwc27t9mexifBeA1cWCpbOVw+7TFcwrNCwuWoyFsJMoMm/wBYnaMDfRzFUT7vyqViA/9x5ROHiVWpjhoyVW+aY=
  bucket: tool-schema-registry
  local-dir: deploy
  acl: ''
  on:
    repo: octoblu/flow-json-schema
    tags: true
