language: node_js
node_js:
- '5'
before_deploy:
- ./node_modules/gulp/bin/gulp.js build
- mkdir -p deploy/$TRAVIS_TAG
- cp dist/schema-registry.json deploy/$TRAVIS_TAG
- cp dist/schema-registry.json deploy/
deploy:
  provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: CP47jV1IKignSNgyZT2T6YbPSOFnaJ46NLNqSYeLpMW2q8jWTMOfCxpPUnapP1FPm/sZd39iUPtnZmTjMGP9qYoJECZZOI++f2KHcpwUlZOlAFq5GAk5gUe/uOfk4wd8Rgk5Xr4r07yIjUN3J2J5KJ6wuBKmAROP35xSXIdCq5xpMqLQVSJX9HLPnamr+tlpY9GICBZoP7NVBjlDoLwaNqYIFyJUyo6Hmmk0A+/nhr5+XL5Z09h5n4KjJuTE/fFhIYoj6XWo3ZWubEDYcXTU2JZfdMpZWUG3L/9dhUFxXcNHJm+p1jvuiV2Aoi1MEZytZKSdioJTH1gwkKzZmuf5SgEO8T5mdVt93pq/duwbqoi2LFDaNDD7j2HCUDekpKMjLhTb3/uQEs8ya7efaUvA40IPrjPQ6bSx2OctN7eTMr+Q6AR68AoBEkjmlIe95/Ko6+YI7gkeIh7opCarpEE5QtTX/v0W5S8hzGGv2TfPk4qwQam8+kb7/+hGUMxOC2zvwgDJY6dITRuO9zsmfr1hAQiibKR9Ok4pdBeegtwBQz97cHzUjBa6c+vqfmo8PTSG8VEh132amQF5E1b9dJyVUBQmaKG9oWEkRe/gK8YKZ/19xTKPxzIycDKZ92ExQCfkrZxkrX2807rjJKX2cjHS6pN7Ci5yBLqBzthkTWUdSl4=
  bucket: tool-schema-registry
  region: us-west-2
  local-dir: deploy
  on:
    tags: true
    all_branches: true
  api_key:
    secure: mx8sUe+b7194nlUdrQb+USg6GQVQSt9jo/a4hPTMGsziAxQ4pit5Y19Kw/AsAV0d+1dcWDx4bKiGOlgqk1Jx7epvvpDdbKsSlRNXOHSchOspi33wTMx7dMR/tzPeztuc79KBOkzxpwcmNv5sUOS3TJ4Ps3viCj4GQ0iykPGo5mMr/WNqv8vHmutlfhxB8p38usWr3Ndu4vMGCi9KaUlKJOR61VCi+r1/vSEwclPQy6RaDWVuIaPBURNwqWx4W/EVrkrJTypMo8jxZNAfWfNsCQHos28AvBgZLkNGF2r44Weafvjrc+kSeq7fWRCH9TrsoNgWPdZWdP/6WzpMyyDDvguZvVStTFPfbO6/4dTvuPipOvqLptuT2FO5+nsdD15VxgyHvDp9jfvkTIua4W+qqkc7mXEfX/eFeumi9O3WxVkxEYB3zauOrTcLMXmr5dc4FrRwZQ5MuFC/tACyzX1VNLhmdC3xstKCWjq7QufiJDp4w2tLpsJR5ezXAt10zMZgdebDHtnN5Qaq1Edgb/gWXeRkzQM0Wc3bTLQAoDkyi7+LJiG6Y+A9iBVEur96N5BKqQeQ1UuxGYdWPi6mn8Ovb6nOPhpLE+7ghaTScLYHPSaSZ09Gs2hchZJhn4Ba9BCg2TH6YAbDvV/Kh+Ex3xaJBO4xnvIXdx3Qj6DX3VN4kPg=
